# -*- coding: utf-8 -*-
"""predict_heart_risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkeenbYjZFvNz92FCcaexgWGr-Sv7rZI
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile predict_heart_risk.py
# import pandas as pd
# import joblib
# 
# 
# model = joblib.load('heart_model_final.pkl')
# scaler = joblib.load('heart_scaler.pkl')
# 
# feature_cols = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
#                 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
# 
# def predict_heart_risk(patient_data):
#     input_df = pd.DataFrame([patient_data])
# 
# 
#     categorical_map = {
#         'cp': {0:0, 1:1, 2:2, 3:3},
#         'fbs': {False:0, True:1},
#         'restecg': {0:0, 1:1, 2:2},
#         'exang': {False:0, True:1},
#         'slope': {0:0, 1:1, 2:2},
#         'thal': {1:0, 2:1, 3:2}
#     }
# 
#     for col, mapping in categorical_map.items():
#         input_df[col] = input_df[col].map(mapping).fillna(0)
# 
#     for col in feature_cols:
#         input_df[col] = pd.to_numeric(input_df[col], errors='coerce').fillna(0)
# 
#     input_scaled = scaler.transform(input_df[feature_cols])
#     probability = model.predict_proba(input_scaled)[0][1]
#     prediction = model.predict(input_scaled)[0]
# 
#     if probability > 0.70:
#         risk = " HIGH RISK - Emergency Tests!"
#     elif probability > 0.40:
#         risk = " MEDIUM RISK - Urgent Checkup"
#     else:
#         risk = " LOW RISK - Healthy Heart"
# 
#     return {
#         'disease_probability': f"{probability:.1%}",
#         'prediction': 'Heart Disease' if prediction == 1 else 'Healthy',
#         'risk_level': risk,
#         'action': 'Cardiologist NOW!' if probability > 0.70 else 'Annual checkup'
#     }
# 
# # Test
# if __name__ == "__main__":
#     patient = {'age':65,'sex':1,'cp':2,'trestbps':150,'chol':250,'fbs':1,
#                'restecg':0,'thalch':120,'exang':1,'oldpeak':2.5,'slope':2,'ca':2,'thal':3}
#     print(predict_heart_risk(patient))
#